name: Docker build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish to Registry
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: ${{ github.REPOSITORY }}/achieve-api
#        username: ${{ secrets.REGISTRY_USERNAME }}
#        password: ${{ secrets.REGISTRY_TOKEN }}
#        registry: docker.pkg.github.com
#        tags: "latest,${{ github.SHA }}"

  deploy:
    runs-on: whale
    #needs: build
    steps:
    - name: Login to packages
      run: |
        whoami
        echo  ${{ secrets.REGISTRY_TOKEN }} |  docker login docker.pkg.github.com -u ${{ github.ACTOR }} --password-stdin
    - uses: actions/checkout@master
    - name: deploy
      run: |
        docker-compose up -d
