name: Docker build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.REPOSITORY }}/achieve-api
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
        registry: docker.pkg.github.com
        tags: "latest,${{ github.SHA }}"
    - name: Deploy package
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          EDGE_API_TOKEN: ${{API_TOKEN}}
          EDGE_ADDRESS: ${{EDGE_ADDRESS}}
          DB_CONN_STRING: ${{DB_CONN_STRING}}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN, EDGE_API_TOKEN, EDGE_ADDRESS, DB_CONN_STRING
        script: |
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_USERNAME --password-stdin
          docker-compose up -d
